### ISSUE TITLE
ACTION LIST Friday

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_experiments#7]
### Experiments results without metacontrol
  - [x] @marioney put the resulting data about configs on a table https://github.com/rosin-project/mros1_reasoner/issues/10

### Experiments with metacontrol
 - Carlos and Mario sync
   - [x] @chcorbato check needs for experiments with metacontrol
   -  [x] Observer for Objective error: needed for scenarios 3 in yellow table
    - [x] @marioney and @chcorbato agree on a solution https://github.com/rosin-project/metacontrol_sim/issues/40

### Paper
  - [x] observers content for 3 and 4 @darkobozhinoski https://github.com/rosin-project/metacontrol_models_paper/issues/21
  - [x] review 5 based on Experiments results without metacontrol @darkobozhinoski and draft version WITH metacontrol
     - [x] identify and list conflicts paper vs experiments and discuss with the rest at 14.00

@darkobozhinoski @marioney please update/modify as you see it fit

**Comment by chcorbato** [comment]
> [ ] @chcorbato check needs for experiments with metacontrol

These are the current needs to run the experiments with metacontrol:
- [x] load `mros1_reasoner/scripts/kb.owl` owl file for `mros1_reasoner`, `instead of mvp.owl`, do you have an issue for this @marioney 
- [ ] **ERROR `== RECONFIGURATION UNKNOWN ==`**: https://github.com/rosin-project/mros1_reasoner/issues/39:

- launch the initial configuration with which we initialize all MAPE-K nodes, which requires:
  - [x] https://github.com/rosin-project/mros1_reasoner/issues/28
  - [x] https://github.com/rosin-project/metacontrol_experiments/issues/8

**Comment by chcorbato** [comment]
> * [x]  @marioney and @chcorbato agree on a solution

Implement an Observer like for a QA but producing a `boolean` value (`True` objective in error, `False` objective NOT in error)
See https://github.com/rosin-project/metacontrol_sim/issues/40

**Comment by marioney** [comment]
>     * load `mros1_reasoner/scripts/kb.owl` owl file for `mros1_reasoner`, `instead of mvp.owl`, do you have an issue for this @marioney

No, can you please create it and assign it to  me.

**Comment by chcorbato** [comment]
> > ```
> > * load `mros1_reasoner/scripts/kb.owl` owl file for `mros1_reasoner`, `instead of mvp.owl`, do you have an issue for this @marioney
> > ```
> 
> No, can you please create it and assign it to me.

No need, I fixed it: https://github.com/rosin-project/metacontrol_experiments/commit/b3c438ececc9f9052dc2bd3af7dde3704d99745f

**Comment by chcorbato** [comment]
Closed, deprecated issues.
